import { createRouter, createWebHashHistory } from "vue-router";

const routes: Array<any> = [
  {
    path: "/login",
    name: "login",
    meta: { name: "登录", isHidden: true, cache: false },
    component: () => import("@/views/login/login.vue"),
  },
  {
    path: "/pluginSearch",
    name: "pluginSearch",
    meta: { name: "应用查询" },
    component: () => import(/* webpackChunkName: "about" */ "/src/views/plugins/pluginSearch.vue"),
  },
  {
    path: "/plugin",
    name: "plugin",
    meta: { name: "插件应用(独立窗口)" },
    component: () => import("@/views/plugins/index.vue"),
    redirect: "/clipboard",
    children: [
      {
        path: "/clipboard",
        name: "clipboard",
        meta: {
          id: 1,
          label: "剪贴板",
          description: "获取和管理剪贴板内容",
          icon: "pluginIcons-剪贴板",
          shortcut: "Ctrl+1",
          type: "tool",
          showHeader: true,
        },
        component: () => import("@/views/plugins/clipboard/index.vue"),
      },
      {
        path: "/fileHasher",
        name: "fileHasher",
        meta: {
          id: 2,
          label: "哈希计算",
          description: "多种算法的哈希计算",
          icon: "pluginIcons-哈希",
          ico: "icons/哈希.ico",
          shortcut: "Alt+F",
          type: "tool",
          showHeader: true,
        },
        component: () => import("@/views/plugins/fileHasher/index.vue"),
      },
      {
        path: "/jsonEditor",
        name: "jsonEditor",
        meta: {
          id: 3,
          label: "JSON 格式化",
          description: "格式化和验证 JSON 数据",
          icon: "pluginIcons-json",
          ico: "icons/json.ico",
          shortcut: "Ctrl+R",
          type: "tool",
          showHeader: true,
        },
        component: () => import("@/views/plugins/jsonEditor/index.vue"),
      },
      {
        path: "/sqlConverter",
        name: "sqlConverter",
        meta: {
          id: 4,
          label: "sql日志转换",
          ico: "icons/sql.ico",
          description: "用于docker日志的sql转化",
          icon: "pluginIcons-sql",
          shortcut: "Ctrl+Alt+5",
          type: "tool",
          showHeader: true,
        },
        component: () => import("@/views/plugins/sqlConverter/index.vue"),
      },
      {
        path: "/nginxFormater",
        name: "nginxFormater",
        meta: {
          id: 5,
          label: "nginx格式化",
          ico: "icons/nginx.ico",
          description: "nginx格式化",
          icon: "pluginIcons-nginx",
          shortcut: "Ctrl+N",
          type: "tool",
          showHeader: true,
        },
        component: () => import("@/views/plugins/nginxFormater/index.vue"),
      },
      {
        path: "/systemInfo",
        name: "systemInfo",
        meta: {
          id: 6,
          label: "系统信息",
          description: "系统信息",
          icon: "pluginIcons-系统信息",
          ico: "icons/系统信息.ico",
          shortcut: "Ctrl+Alt+4",
          type: "tool",
          showHeader: true,
        },
        component: () => import("@/views/plugins/systemInfo/index.vue"),
      },
      {
        path: "/fileTreeJson",
        name: "fileTreeJson",
        meta: {
          id: 7,
          label: "文件树",
          description: "文件树",
          icon: "pluginIcons-文件树",
          ico: "icons/文件树.ico",
          shortcut: "Ctrl+T",
          type: "tool",
          showHeader: true,
        },
        component: () => import("@/views/plugins/fileTreeJson/index.vue"),
      },
      {
        path: "/fileOrganizer",
        name: "fileOrganizer",
        meta: {
          id: 8,
          label: "文件整理",
          description: "文件整理",
          icon: "pluginIcons-文件整理",
          ico: "icons/文件整理.ico",
          shortcut: "Ctrl+Alt+3",
          type: "tool",
          showHeader: true,
        },
        component: () => import("@/views/plugins/fileOrganizer/index.vue"),
      },
      {
        path: "/batchRegex",
        name: "batchRegex",
        meta: {
          id: 9,
          label: "批量正则",
          description: "批量正则",
          icon: "pluginIcons-正则",
          ico: "icons/正则.ico",
          shortcut: "Ctrl+Alt+1",
          type: "tool",
          showHeader: true,
        },
        component: () => import("@/views/plugins/batchRegex/index.vue"),
      },
      {
        path: "/codeGenerator",
        name: "codeGenerator",
        meta: {
          id: 10,
          label: "代码生成",
          description: "代码生成",
          icon: "pluginIcons-代码",
          ico: "icons/代码.ico",
          shortcut: "Ctrl+Alt+2",
          type: "tool",
          showHeader: true,
        },
        component: () => import("@/views/plugins/codeGenerator/index.vue"),
      },
      {
        path: "/colorExtraction",
        name: "colorExtraction",
        meta: {
          id: 11,
          label: "取色",
          description: "取色",
          icon: "pluginIcons-取色",
          ico: "icons/取色.ico",
          shortcut: "Alt+1",
          type: "tool",
          showHeader: false,
          transparent: true,
          fullscreen: true,
          alwaysOnTop: true,
          newWindow: true,
        },
        component: () => import("@/views/plugins/colorExtraction/index.vue"),
      },
      {
        path: "/screenshot",
        name: "screenshot",
        meta: {
          id: 12,
          label: "截图",
          description: "截图",
          icon: "pluginIcons-截图",
          shortcut: "Ctrl+W",
          showHeader: false,
          transparent: true,
          type: "tool",
          fullscreen: true,
          skipTaskbar: true,
          alwaysOnTop: false,
          newWindow: true,
          closeHiden: true,
        },
        component: () => import("@/views/plugins/screenshot/index.vue"),
      },
      {
        path: "/screenshotAndSuspended",
        name: "screenshotAndSuspended",
        meta: {
          id: 13,
          label: "截图并悬浮",
          description: "截图并悬浮",
          icon: "pluginIcons-截图并悬浮",
          shortcut: "Ctrl+Q",
          showHeader: false,
          transparent: true,
          skipTaskbar: true,
          type: "tool",
          fullscreen: true,
          alwaysOnTop: false,
          newWindow: true,
        },
        component: () => import("@/views/plugins/screenshotAndSuspended/index.vue"),
      },

      {
        path: "/translation",
        name: "translation",
        meta: {
          id: 15,
          label: "翻译",
          description: "翻译",
          icon: "pluginIcons-翻译",
          shortcut: "Ctrl+E",
          showHeader: true,
          transparent: false,
          type: "tool",
          fullscreen: false,
          alwaysOnTop: false,
          newWindow: false,
          width: 800,
          height: 250,
        },
        component: () => import("@/views/plugins/translation/index.vue"),
      },
      {
        path: "/image",
        name: "image",
        meta: { id: 101, hideen: true, name: "图片", description: "图片", type: "assist", showHeader: false },
        component: () => import("@/views/plugins/image/index.vue"),
      },
    ],
  },
  {
    path: "/manage",
    name: "manage",
    meta: { name: "设置", isHidden: true },
    component: () => import("/src/views/manage/index.vue"),
    children: [
      {
        path: "/person",
        name: "person",
        meta: {
          label: "个人中心",
          isHidden: true,
          svgIcon: "pluginSvg-sql",
          src: "/images/manageImages/用户.png",
          affix: true,
        },
        children: [
          {
            path: "/account",
            name: "account",
            meta: {
              label: "我的账号",
              isHidden: true,
              svgIcon: "pluginIcons-sql",
              src: "/images/manageImages/用户.png",
              affix: true,
            },
            component: () => import("/src/views/manage/account/index.vue"),
          },

          {
            path: "/localData",
            name: "localData",
            meta: {
              label: "本地数据",
              isHidden: true,
              svgIcon: "pluginSvg-sql",
              src: "/images/manageImages/用户.png",
              affix: true,
            },
            component: () => import("/src/views/manage/localData/index.vue"),
          },
        ],
      },
      {
        path: "/Preference",
        name: "Preference",
        meta: {
          label: "偏好设置",
          isHidden: true,
          svgIcon: "pluginSvg-sql",
          src: "/images/manageImages/用户.png",
          affix: true,
        },
        children: [
          {
            path: "/config",
            name: "config",
            meta: {
              label: "设置",
              isHidden: true,
              svgIcon: "pluginSvg-设置",
              src: "/images/manageImages/设置.png",
              affix: true,
            },
            component: () => import("/src/views/manage/config/index.vue"),
          },
          {
            path: "/aiModel",
            name: "aiModel",
            meta: {
              label: "AI管理",
              isHidden: true,
              svgIcon: "pluginSvg-设置",
              src: "/images/manageImages/设置.png",
              affix: true,
            },
            component: () => import("/src/views/manage/aiModel/index.vue"),
          },
          {
            path: "/database",
            name: "database",
            meta: {
              label: "数据库管理",
              isHidden: true,
              svgIcon: "pluginSvg-设置",
              src: "/images/manageImages/设置.png",
              affix: true,
            },
            component: () => import("/src/views/manage/database/index.vue"),
          },
          {
            path: "/shortcut",
            name: "shortcut",
            meta: {
              label: "快捷方式",
              isHidden: true,
              svgIcon: "pluginSvg-sql",
              src: "/images/manageImages/用户.png",
              affix: true,
            },
            component: () => import("/src/views/manage/shortcut/index.vue"),
          },
        ],
      },
    ],
  },
];
const router = createRouter({
  history: createWebHashHistory("/"),
  routes,
});

export default router;
export { routes };
